# This file was generated by Limelight.
# It is automtically added to frozen gems.  When Limelight loads a production, it will load all 'limelight_init.rb'
# files, like this one, in each of the frozen gems.

Limelight::Gems.install('aquarium-0.4.3', ["lib"])
